# Generated by Django 3.1.1 on 2020-09-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
